version: "3.8"

services:
  db:
    image: postgres:16
    platform: linux/amd64
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
      - /etc/localtime:/etc/localtime:ro  # 호스트 시스템의 시간을 공유
    env_file:
      - backend/.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    platform: linux/amd64
    restart: always
    ports:
      - "6379:6379"

volumes:
  app-db-data:
