"""Add User and UserLocation models

Revision ID: c848793be054
Revises: 13a5f2ae708a
Create Date: 2024-08-29 22:33:55.328454

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "c848793be054"
down_revision: Union[str, None] = "13a5f2ae708a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
